export const REMOVE_LS_PRODUCT_REQUEST = 'REMOVE_LS_PRODUCT_REQUEST';
export const REMOVE_LS_PRODUCT_SUCCESS = 'REMOVE_LS_PRODUCT_SUCCESS';
export const REMOVE_LS_PRODUCT_FAIL = 'REMOVE_LS_PRODUCT_FAIL';